baseURL = "/"
languageCode = "en-us"
title = "Welledy"
themesDir = "themes"
theme = "hugo-hero-theme"

[params]
  google_analytics_id=""

  [params.homepage_meta_tags]
    meta_description = ""
    meta_og_title = "Welledy"
    meta_og_type = "website"
    meta_og_url = "https://www.welledy.com"
    meta_og_image = "https://www.welledy.com/images/wy-masthead-with-outline.jpg"
    meta_og_description = ""
    meta_twitter_card = "summary"
    meta_twitter_site = "@WelledyHealth"
    meta_twitter_creator = "@WelledyHealth"

# [[menu.main]]
# 	name = "Services"
# 	url = "/services/"
#     weight = 1

# [[menu.main]]
#     name = "Work"
#     url = "/work/"
#     weight = 2

# [[menu.main]]
#     name = "About"
#     url = "/about/"
#     weight = 3

# [[menu.main]]
#     name = "Contact"
#     url = "/contact/"
#     weight = 4

# [permalinks]
#   post = "/:year/:month/:day/:slug/"
#   pages = "/:filename/"
